# Generated by Django 4.2.3 on 2023-07-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome ')),
                ('codigo', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Código ')),
            ],
        ),
    ]
