# Generated by Django 4.2.3 on 2023-07-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Código ')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome ')),
                ('email', models.EmailField(max_length=80, verbose_name='Email ')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço ')),
                ('numero', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Numero ')),
                ('tel', models.DecimalField(decimal_places=11, max_digits=15, verbose_name='Telefone ')),
            ],
        ),
    ]
