# Generated by Django 4.2.3 on 2023-07-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_fornecedor_numero_alter_fornecedor_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='numero',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Numero '),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='tel',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Telefone '),
        ),
    ]
