# Generated by Django 4.2.3 on 2023-07-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_fornecedor_numero_alter_fornecedor_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cores',
            name='codigo',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Código '),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='codigo',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Código '),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='numero',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Numero : '),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Preco '),
        ),
    ]
