# Generated by Django 4.2.3 on 2023-07-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cores_codigo_alter_fornecedor_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tributacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfop', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Cfop ')),
                ('ncm', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Ncm ')),
                ('cst', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Cst ')),
            ],
        ),
    ]
