# Generated by Django 4.2.3 on 2023-08-04 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tributacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codvenda', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Código Venda ')),
                ('codprod', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Código Produto')),
                ('sku', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Sku ')),
                ('tamanho', models.CharField(max_length=10, verbose_name='Tamanho ')),
                ('cor', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Cor ')),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Quantidade ')),
                ('valor', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Valor ')),
                ('troco', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Troco ')),
                ('desconto', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Desconto ')),
                ('acrescimo', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Acrescimos ')),
                ('pagamento', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Pagamento ')),
                ('cliente', models.CharField(max_length=50, verbose_name='Cliente ')),
                ('formapag', models.CharField(max_length=40, verbose_name='Forma de Pagamento ')),
                ('parcelas', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Parcelas ')),
                ('vendedor', models.CharField(max_length=50, verbose_name='Vendedor ')),
                ('codvendedor', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Código Vendedor ')),
                ('caixa', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Caixa ')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Nfe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateField()),
                ('invite_reason', models.CharField(max_length=64)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('cores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cores')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pagamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
                ('tributacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tributacao')),
                ('vendas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vender')),
            ],
        ),
    ]
